### ISSUE TITLE
Obtuse Error message

### ISSUE THREAD

**Issue by ForsythsGambit** [lxmx/PyPlucker#1]
I attempted the following, to a rather obtuse error message 
`root@DESKTOP-43CABDP:~# plucker-build --bpp=4 --maxdepth=5 --doc-file=ArmageddonDocs -H https://www.armageddon.org/intro/new_to_muds.php

`Pluckerdir is '/root/.plucker'...
---- 0 collected, 1 to do ----
Processing https://www.armageddon.org/intro/new_to_muds.php...
Traceback (most recent call last):
  File "/usr/local/bin/plucker-build", line 1923, in <module>
    sys.exit(realmain(None))
  File "/usr/local/bin/plucker-build", line 1915, in realmain
    retval = main (config, exclusion_lists)
  File "/usr/local/bin/plucker-build", line 1279, in main
    spider.process_all(verbose=verbosity)
  File "/usr/local/bin/plucker-build", line 760, in process_all
    self.process (verbose, estimate, statusfile)
  File "/usr/local/bin/plucker-build", line 887, in process
    message("  Retrieval failed: %s -- %s." % (code, text))
  File "/usr/lib/python2.7/site-packages/PyPlucker/UtilFns.py", line 48, in message
    raise ValueError("call to 'message' with no format argument -- " + str(args[0]) + " found instead")
ValueError: call to 'message' with no format argument --   Retrieval fail`

The example command in the readme ran just fine and is viewable but when substituting in the url `https://www.armageddon.org/intro/new_to_muds.php` it out put the following. Any guidance is appreciate.

**Comment by ForsythsGambit** [comment]
hmmm, thats not preserving formatting. try this: 
![image](https://user-images.githubusercontent.com/56049633/165009149-b36ff90d-f8cb-40fa-90e3-fda9826d4e7a.png)

**Comment by ForsythsGambit** [comment]
Running percolate seems to have sorted it. Still no idea why the original build failed though.

**Comment by ForsythsGambit** [comment]
Well, now that I've tested percolate that doesn't work either :/

**Comment by vaskas** [comment]
Hey, thanks for using PyPlucker!

The issue is with the server's SSL certificate, it has an incomplete chain (https://www.ssllabs.com/ssltest/analyze.html?d=www.armageddon.org). See https://stackoverflow.com/questions/46604114/python-requests-ssl-error-certificate-verify-failed for an explanation.

Doing `export PYTHONHTTPSVERIFY=0` before `plucker-build` fixes that for this particular server, just don't persist this environment variable :) There should be a similar way for Node.js / percollate.

**Comment by ForsythsGambit** [comment]
Got it, thank you for the quick reply! I’ll give that a try when I get the chance. :D
